[build]
  command = "npm install --legacy-peer-deps && npx prisma generate && npm run build"
  publish = ".next"   # <--- aqui

[dev]
  command = "npm run dev"
  port = 3000

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"