[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "."
  # ou use "out" apenas se estiver usando `next export`

[dev]
  command = "npm run dev"
  port = 3000

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"